Image updates
dscho/git-scm.com pull request #16
Opened 2024-11-28 07:55 UTC by TheGiraffe3

Related to my comment on the Dark Mode pull request you have.
I'm not done with all of the images, they may take a while, but wanted to make sure this was what you were thinking of.
Thoughts?

2024-12-02 11:10 UTC, dscho requested changes
Awesome work!

Could you describe your process, though? Maybe part of it is automatable.

In addition, I noticed that some details are lost, for example the rays in the Eclipse logo.

2024-12-02 11:10 UTC, dscho commented on static/images/company-project-logos/postgresql@2x.png
This one seems to have lost the upper left corner of the "P"...

2024-12-02 11:12 UTC, TheGiraffe3 commented
I was using [GIMP](https://www.gimp.org), so I don't think it's automatable.

2024-12-02 11:21 UTC, dscho commented
> I was using [GIMP](https://www.gimp.org), so I don't think it's automatable.

Fair enough.

Considering in particular the PostgreSQL logo in [the screenshot](https://github.com/git/git-scm.com/pull/1888#issuecomment-2510656771), what would you think about [the idea to always use a light background for those logos, even in Dark Mode](https://github.com/git/git-scm.com/pull/1888#issuecomment-2508883708), instead?

2024-12-02 12:23 UTC, TheGiraffe3 commented
That could work, but from what little I know of GIMP it would be quite a bit more difficult to add backgrounds then remove them.
I can try, but I'm not sure it'll work well (or look good on the website when that's in dark mode).

2024-12-02 12:54 UTC, TheGiraffe3 commented
Been trying: the Eclipse logo is pretty hard to effectively remove the background of while keeping all the rays.
Would it be allowable to get a different logo to remove the background of?

2024-12-03 07:41 UTC, dscho commented
> Been trying: the Eclipse logo is pretty hard to effectively remove the background of while keeping all the rays.
> Would it be allowable to get a different logo to remove the background of?

I guess that Eclipse actually changed their logo in 2014, removing those rays. At least that's how it would appear when looking at https://www.eclipse.org/org/artwork/. If you download the IDE-related logo archive, you actually get an SVG, which should be a lot easier to work with than a PNG.

And on the IDE's homepage, they use https://eclipseide.org/images/logo/eclipse-ide-logo-white.svg... which we could theoretically use as-is.

2024-12-03 10:36 UTC, dscho commented on static/images/company-project-logos/eclipse@2x.png
This looks great!

For the record, it seems that the Git homepage already missed [an important update of Eclipse's logo in 2010 "to help broaden the appeal of the Eclipse to a younger demographic"](https://web.archive.org/web/20100404070643/http://www.eclipse.org/org/press-release/20100401_newlogo.php).

But the latest update of that logo happened [on Feb 13, 2014](https://blogs.eclipse.org/post/anonymous/introducing-updated-eclipse-logo) and is indeed reflected by this here commit.

2024-12-03 10:36 UTC, dscho approved these changes
Thank you so much!

2024-12-03 10:37 UTC, TheGiraffe3 commented
Happy to help.

2024-12-03 10:42 UTC, merged